---
version: "2.1"
services:
  readarr01:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/readarr01:/config
      - /disk2/books:/books #optional
      - /disk2/torrents:/torrents #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  readarr02:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/readarr02:/config
      - /disk2/books:/books #optional
      - /disk2/torrents:/torrents #optional
    ports:
      - 8788:8787
    restart: unless-stopped