---
version: "2.1"
services:
  readarr01:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/readarr01:/config
      - /disk2/books:/books
      - /disk2/torrents:/torrents
    expose:
      - 8787
    restart: unless-stopped
  readarr02:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr02
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/readarr02:/config
      - /disk2/books:/books
      - /disk2/torrents:/torrents
    expose:
      - 8787
    restart: unless-stopped
  calibreweb01:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibreweb01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /disk2/config/calibreweb01:/config
      - /disk2/config/readarr01:/books
    expose:
      - 8083
    restart: unless-stopped
  calibre01:
    image: lscr.io/linuxserver/calibre
    container_name: calibre01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=
      - CLI_ARGS=
      - SUBFOLDER=/calibre/
    volumes:
      - /disk2/config/calibre01:/config
      - /disk2/config/readarr01:/books
    expose:
      - 8080
      - 8081
    restart: unless-stopped
networks:
  default:
    external:
      name: shared