---
version: "2.1"
services:
  powlarr01:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: powlarr01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/powlarr01/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
networks:
  default:
    external:
      name: shared