version: "2.1"
services:
  plex01:
    image: lscr.io/linuxserver/plex
    container_name: plex01
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= ${CLAIM}
    volumes:
      - /disk3/plex01/config:/config
      - /disk1/plex/transcoder:/transcoder
      - /disk3/plex/tv:/tv
      - /disk3/plex/tvarchive:/tvarchive
      - /disk2/plex/movies:/movies
    restart: unless-stopped
    ports:
      - 32400:32400
networks:
  default:
    external:
      name: shared