---
version: "2.1"
services:
  radarr01:
    image: lscr.io/linuxserver/radarr
    container_name: radarr01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/radarr01:/config
      - /disk3/plex/movies:/movies
      - /disk2/torrents:/torrents
    ports:
      - 7878:7878
    restart: unless-stopped
networks:
  default:
    external:
      name: shared