version: "3"
services:
  flexget01:
    image: wiserain/flexget
    container_name: flexget01
    restart: on-failure:5
    ports :
      - 5051:5050
    volumes:
      - /disk2/flexget/data:/data
      - /disk2/config/flexget01:/config
      - /disk2/torrents:/torrents
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - FG_WEBUI_PASSWD=@{PASSWORD}
networks:
  default:
    external:
      name: shared