---
version: "2.1"
services:
  jackett01:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett01
    expose:
      - 9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /disk2/config/jackett01:/config
      - /disk2/torrents/:/torrents
    restart: unless-stopped
networks:
  default:
    external:
      name: shared