---
version: "2.1"
services:
  deluge01:
    image: lscr.io/linuxserver/deluge
    container_name: deluge01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /disk2/config/deluge01:/config
      - /disk2/torrents:/torrents
    ports:
      - 8101:8112
      - 6101:60881
      - 6101:60881/udp
    restart: unless-stopped
  deluge02:
    image: lscr.io/linuxserver/deluge
    container_name: deluge02
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /disk2/config/deluge02:/config
      - /disk2/torrents:/torrents
    ports:
      - 8102:8112
      - 6102:60881
      - 6102:60881/udp
    restart: unless-stopped
  deluge03:
    image: lscr.io/linuxserver/deluge
    container_name: deluge03
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /disk2/config/deluge03:/config
      - /disk2/torrents:/torrents
    ports:
      - 8103:8112
      - 6103:60881
      - 6103:60881/udp
    restart: unless-stopped
  deluge04:
    image: lscr.io/linuxserver/deluge
    container_name: deluge04
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /disk2/config/deluge04:/config
      - /disk2/torrents:/torrents
    ports:
      - 8104:8112
      - 6104:60881
      - 6104:60881/udp
    restart: unless-stopped
  deluge05:
    image: lscr.io/linuxserver/deluge
    container_name: deluge05
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /disk2/config/deluge05:/config
      - /disk2/torrents:/torrents
    ports:
      - 8105:8112
      - 6105:60881
      - 6105:60881/udp
    restart: unless-stopped
  deluge06:
    image: lscr.io/linuxserver/deluge
    container_name: deluge06
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /disk2/config/deluge06:/config
      - /disk2/torrents:/torrents
    ports:
      - 8106:8112
      - 6106:60881
      - 6106:60881/udp
    restart: unless-stopped
  deluge07:
    image: lscr.io/linuxserver/deluge
    container_name: deluge07
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /disk2/config/deluge07:/config
      - /disk2/torrents:/torrents
    ports:
      - 8107:8112
      - 6107:60881
      - 6107:60881/udp
    restart: unless-stopped