---
version: "2.1"
services:
  mylar01:
    image: lscr.io/linuxserver/mylar3
    container_name: mylar01
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /disk2/config/mylar01:/config
      - /disk2/books/comics:/comics
      - /disk2/torrents:/torrents
    ports:
      - 8890:8090
    restart: unless-stopped