#This compose file adds diagrams.net (ex draw.io) to your stack
version: '3.5'
services:
  draw01:
    image: jgraph/drawio:latest
    container_name: draw01
    restart: unless-stopped
    expose:
      - 8080
    environment:
      PUBLIC_DNS: domain
      ORGANISATION_UNIT: unit
      ORGANISATION: org
      CITY: city
      STATE: state
      COUNTRY_CODE: country
networks:
  default:
    external:
      name: shared