version: "2.1"
services:
  medusa:
    image: lscr.io/linuxserver/medusa:latest
    container_name: medusa01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/medusa01:/config
      - /disk2/torrents:/torrents
      - /disk3/plex/tv:/tv
    expose:
      - 8081
    restart: unless-stopped
networks:
  default:
    external:
      name: shared