---
version: "2.1"
services:
  dokuwiki01:
    image: lscr.io/linuxserver/dokuwiki
    container_name: dokuwiki01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /disk2/config/dokuwiki01:/config
    expose:
      - 80
    restart: unless-stopped
networks:
  default:
    external:
      name: shared